<a href="https://colab.research.google.com/github/priyal6/DL/blob/main/dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [8]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [9]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-0.79184629, -0.04894726, -0.8216477 , ..., -0.68738624,
        -0.78594774, -0.96088757],
       [-0.59970258,  2.06782298, -0.62099424, ..., -0.66374344,
        -0.71293296, -0.11389242],
       [-0.39085072, -0.58792902, -0.38925361, ..., -0.52203915,
         0.25645483,  0.0840852 ],
       ...,
       [-0.78627691, -1.17297759, -0.82205143, ..., -1.57971138,
        -0.22979257, -1.09996276],
       [ 3.22367878, -0.41287511,  3.3125404 , ...,  2.45466599,
         1.21807509,  0.22479656],
       [ 1.34958143, -0.07889069,  1.26159552, ...,  0.10868981,
        -0.10085157, -1.01542686]])

In [13]:
y_train

67     B
452    B
519    B
72     M
116    B
      ..
201    M
460    M
276    B
352    M
127    M
Name: diagnosis, Length: 455, dtype: object

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [18]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [19]:
X_train_tensor.shape

torch.Size([455, 30])

In [20]:
y_train_tensor.shape

torch.Size([455])

In [22]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return len(self.features)
  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [23]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [26]:
train_dataset[10]

(tensor([-0.3073, -1.2467, -0.3812, -0.3540, -0.9020, -1.2422, -1.0567, -1.0212,
         -1.3047, -1.0759, -0.0428, -0.6989, -0.1617, -0.1701, -0.9501, -1.1508,
         -1.0802, -1.1881, -0.7694, -0.5979, -0.3213, -1.3219, -0.3977, -0.3674,
         -1.3355, -1.2288, -1.2215, -1.2104, -1.2411, -0.9942]),
 tensor(0.))

In [25]:
test_dataset[50]

(tensor([ 1.2432e-01,  9.2997e-01,  7.3420e-02,  1.6706e-02, -6.6795e-01,
         -7.0583e-01, -5.5829e-02,  9.6907e-02, -6.6524e-01, -1.2204e+00,
          2.0102e-02,  7.4489e-01,  9.5689e-04, -1.7014e-01,  4.0607e-01,
         -4.4981e-01,  9.3637e-02,  6.8003e-01, -3.9171e-01, -3.6244e-01,
         -1.0759e-01,  9.6789e-01, -1.5871e-01, -2.2240e-01, -5.6682e-02,
         -6.0596e-01, -1.6833e-02,  3.2376e-01, -6.6633e-01, -8.5454e-01]),
 tensor(1.))

In [27]:
train_loader = DataLoader(train_dataset, batch_size= 32, shuffle=True )
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle=True)

In [28]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [29]:
learning_rate = 0.1
epochs = 25

In [30]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

loss_function = nn.BCELoss()

In [31]:
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

     y_pred = model(batch_features)

     loss = loss_function(y_pred, batch_labels.view(-1,1))

     optimizer.zero_grad()

     loss.backward()

     optimizer.step()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.12430500239133835
Epoch: 2, Loss: 0.16252882778644562
Epoch: 3, Loss: 0.1481332927942276
Epoch: 4, Loss: 0.16629697382450104
Epoch: 5, Loss: 0.017825108021497726
Epoch: 6, Loss: 0.4505963623523712
Epoch: 7, Loss: 0.06091107800602913
Epoch: 8, Loss: 0.12717166543006897
Epoch: 9, Loss: 0.10193146020174026
Epoch: 10, Loss: 0.058075837790966034
Epoch: 11, Loss: 0.1292313039302826
Epoch: 12, Loss: 0.08250534534454346
Epoch: 13, Loss: 0.14806734025478363
Epoch: 14, Loss: 0.02995557151734829
Epoch: 15, Loss: 0.060574114322662354
Epoch: 16, Loss: 0.019450219348073006
Epoch: 17, Loss: 0.14541815221309662
Epoch: 18, Loss: 0.017805207520723343
Epoch: 19, Loss: 0.026473518460989
Epoch: 20, Loss: 0.06419788300991058
Epoch: 21, Loss: 0.013000006787478924
Epoch: 22, Loss: 0.043220605701208115
Epoch: 23, Loss: 0.004104184918105602
Epoch: 24, Loss: 0.050342824310064316
Epoch: 25, Loss: 0.012011474929749966

In [33]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    predicted_classes = (y_pred > 0.5).float() # Assuming 0.5 as threshold for binary classification

    batch_accuracy = (predicted_classes.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9766