<a href="https://colab.research.google.com/github/priyal6/DL/blob/main/pytorch_training_pipe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(3)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN

In [34]:
df.shape

(569, 33)

In [35]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [36]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

In [38]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
X_train

array([[-0.57158582, -0.11878237, -0.61440951, ..., -0.97196248,
        -0.0187441 , -0.16177108],
       [ 0.25601781, -1.03321528,  0.21511956, ...,  0.01965257,
        -0.33781753, -0.05326517],
       [-0.4326873 , -0.30996104, -0.49871975, ..., -1.5096769 ,
        -1.09395506, -1.62488764],
       ...,
       [-0.09412218,  0.32576561, -0.04685905, ...,  0.65564215,
         0.50639757,  1.79533292],
       [ 2.6780606 ,  1.67092636,  2.83280981, ...,  2.48586156,
         0.50972125,  0.22599478],
       [-0.58894813, -0.86737354, -0.6022537 , ..., -0.57715134,
         0.81051443, -0.2525734 ]])

In [40]:
y_train

346    B
472    B
360    B
87     M
460    M
      ..
333    B
144    B
7      M
202    M
84     B
Name: diagnosis, Length: 455, dtype: object

In [41]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [42]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0])

In [43]:
import torch

In [44]:
#numpy arrays to pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [45]:
X_train_tensor

tensor([[-0.5716, -0.1188, -0.6144,  ..., -0.9720, -0.0187, -0.1618],
        [ 0.2560, -1.0332,  0.2151,  ...,  0.0197, -0.3378, -0.0533],
        [-0.4327, -0.3100, -0.4987,  ..., -1.5097, -1.0940, -1.6249],
        ...,
        [-0.0941,  0.3258, -0.0469,  ...,  0.6556,  0.5064,  1.7953],
        [ 2.6781,  1.6709,  2.8328,  ...,  2.4859,  0.5097,  0.2260],
        [-0.5889, -0.8674, -0.6023,  ..., -0.5772,  0.8105, -0.2526]],
       dtype=torch.float64)

In [46]:
X_train

array([[-0.57158582, -0.11878237, -0.61440951, ..., -0.97196248,
        -0.0187441 , -0.16177108],
       [ 0.25601781, -1.03321528,  0.21511956, ...,  0.01965257,
        -0.33781753, -0.05326517],
       [-0.4326873 , -0.30996104, -0.49871975, ..., -1.5096769 ,
        -1.09395506, -1.62488764],
       ...,
       [-0.09412218,  0.32576561, -0.04685905, ...,  0.65564215,
         0.50639757,  1.79533292],
       [ 2.6780606 ,  1.67092636,  2.83280981, ...,  2.48586156,
         0.50972125,  0.22599478],
       [-0.58894813, -0.86737354, -0.6022537 , ..., -0.57715134,
         0.81051443, -0.2525734 ]])

In [47]:
X_train_tensor.shape

torch.Size([455, 30])

In [48]:
y_train_tensor.shape

torch.Size([455])

In [49]:
#simple model
class MySimpleNN():

  def __init__(self, X): #X is the input data
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor)* torch.log(1-y_pred)).mean()
    return loss

In [50]:
learning_rate = 0.1
epochs = 25

In [52]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.205038762486361
Epoch: 2, Loss: 3.0586690860734462
Epoch: 3, Loss: 2.91369269391573
Epoch: 4, Loss: 2.7664708429178555
Epoch: 5, Loss: 2.615673051170222
Epoch: 6, Loss: 2.458758560025521
Epoch: 7, Loss: 2.2981754886379355
Epoch: 8, Loss: 2.1379070482624773
Epoch: 9, Loss: 1.9729211511252591
Epoch: 10, Loss: 1.8121612780513605
Epoch: 11, Loss: 1.658201776407714
Epoch: 12, Loss: 1.507457816803968
Epoch: 13, Loss: 1.369655487325974
Epoch: 14, Loss: 1.246556060078085
Epoch: 15, Loss: 1.1396397483405405
Epoch: 16, Loss: 1.0497902420730278
Epoch: 17, Loss: 0.976984949420823
Epoch: 18, Loss: 0.9201184797137697
Epoch: 19, Loss: 0.8771008692213723
Epoch: 20, Loss: 0.8452453663117473
Epoch: 21, Loss: 0.8217764014152765
Epoch: 22, Loss: 0.8042449531739588
Epoch: 23, Loss: 0.7907431552850646
Epoch: 24, Loss: 0.7799255867744498
Epoch: 25, Loss: 0.770911485941597

In [53]:
#model evaluation

with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5877193212509155